on:
  issue_comment:
    types: created

name: Configure treadmill
jobs:
  report:
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/test' }}   # check if the comments come from pull request, exclude those from issue.
    name: Configure treadmill
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0       
      - name: Add comment
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['Treadmill']
            })
