on:
  issue_comment:
    types: created

name: Configure treadmill
jobs:
  report:
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/deploy' }}   # check if the comments come from pull request, exclude those from issue.
    name: Configure treadmill
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Set latest commit status as pending
        uses: myrotvorets/set-commit-status-action@master
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending
      - name: Fail randomly
        run: |
          cat README.md
          exit $((RANDOM % 2))        
      - name: Message success
        if: ${{ success() }}
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Deployment succeeded! ✅',
            });          
      - name: Message failure
        if: ${{ failure() }}
        uses: actions/github-script@v4
        with:
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Deployment failed! ❌',
            }); 
